### ISSUE TITLE
Api to Create and apply payments from server side

### ISSUE THREAD

**Issue by SrikarMamidi** [razorpay/razorpay-java#104]
I have integrated razorpay with java and trying to invoke payments(create a payment method and apply payments) directly from the server side since we don't have any front end code. Looks like razor pay is not exposing any api to create a payment directly from server side.

**Comment by ankitdas13** [comment]
@SrikarMamidi Sorry for the long delay. the sdk is updated now. You can use server side payment by using this `create payment json`  api , please check this [doc](https://github.com/razorpay/razorpay-java/blob/master/documents/payment.md#create-payment-json) .

**Comment by ankitdas13** [comment]
Closing this issue for now. if you need any help . Please let us know
