### ISSUE TITLE
Razorpay api Integration

### ISSUE THREAD

**Issue by sharadchavhan001** [razorpay/razorpay-java#116]
sample code for java , api integration,

I am not able to implement using provided reference code,
please provide me best solution for this 

regards,
Sharad

**Comment by Puneet1796** [comment]
Can you tell us which step is causing you trouble to understand the integration?

**Comment by ankitdas13** [comment]
@sharadchavhan001 Apologise for the long delay. Could you please let us know did you succeed in integrating this API ?

**Comment by ankitdas13** [comment]
Closing this issue for now due to not getting any response. If someone is experiencing integration issues, please check this out [doc](https://github.com/razorpay/razorpay-java#usage).
