### ISSUE TITLE
Can not execute the below API using this package.

### ISSUE THREAD

**Issue by nilesh287** [razorpay/razorpay-java#123]
https://api.razorpay.com/v1/orders/order_HD04n5qmSff3Re?expand[]=payments

**Comment by nilesh287** [comment]
Please provide solution for the same ASAP.

**Comment by ankitdas13** [comment]
@nilesh287 Apologise for the long delay. i hope you resolved this issue , but if some are facing this issue you can use this code snippet

`JSONObject orderRequest = new JSONObject();`
 `orderRequest.put("expand[]","payments");`
`Order order = razorpayclient.orders.get("orders/order_KSRYuJpvKDA9of", orderRequest);`

**Comment by ankitdas13** [comment]
Closing this for now. if anyone facing this issue then try this code snippet. please don't let that stop you from re-opening if issue is still persisting for you.
