### ISSUE TITLE
[Feature Request] Adding Allowed Payers In Virtual Account API

### ISSUE THREAD

**Issue by nilayspshah** [razorpay/razorpay-java#136]
**Problem Description**

`VirtualAccountClient` class currently does not support addition of allowed payers for TPV flow as mentioned [here](https://razorpay.com/docs/smart-collect/api/add-tpv/)
Unlike `Payments` there is also no such support for a custom call

```java
Entity response = razorpayClient.Payments.post("path", JSONObject requestBody);
```
The Current `edit` method on the `VirtualAccountClient` is also not applicable 
```java
public VirtualAccount edit(String id, JSONObject request) throws RazorpayException {
        return (VirtualAccount)this.patch(String.format("virtual_accounts/%s", id), request);
    }
```
because it is a `PATCH` call and the add additional payer is a `POST` call
```
/virtual_accounts/{va_id}/allowed_payers
```

Hack:
- we can directly call the `post` on `VirtualAccountClient` just like `Payments` post, but a dedicated a method exposed will make the API richer

**Suggested Solutions**
* create a custom `addAllowedPayers` method

**Comment by ankitdas13** [comment]
@nilayspshah The feature has been added , please check this doc for more [info](https://github.com/razorpay/razorpay-java/blob/master/documents/virtualAccount.md#add-an-allowed-payer-account) and Thanks for your suggestions. 

Thank you for taking the time to contribute

**Comment by ankitdas13** [comment]
Closing this issue for now if you need any help then please let us know.
