### ISSUE TITLE
[Bug] Improper handling of delete call response

### ISSUE THREAD

**Issue by nilayspshah** [razorpay/razorpay-java#137]
## Expected Behavior
When a `delete` call is made, the `ApiClient`'s `processDeleteResponse` should "return" void, if deletion is successful

## Current Behavior
Currently, `ApiClient`'s `processDeleteResponse` returns `JSONException` saying
```
A JSONObject text must begin with '{' at 0 [character 1 line 1]
```

Current Code:
```java 
private void processDeleteResponse(Response response) throws RazorpayException {
        if (response == null) {
            throw new RazorpayException("Invalid Response from server");
        } else {
            int statusCode = response.code();
            String responseBody = null;
            JSONObject responseJson = null;

            try {
                responseBody = response.body().string();
                responseJson = new JSONObject(responseBody);
            } catch (IOException var6) {
                throw new RazorpayException(var6.getMessage());
            }

            if (statusCode < 200 || statusCode >= 300) {
                this.throwException(statusCode, responseJson);
            }

        }
    }
```
for a delete request 204 is a valid response, and the `responseBody` in that case will be empty,
Currently if `responseBody` is empty, then `new JSONObject(responseBody); ` will give `JSONException` as it wont be able to serialize empty string

## Possible Solution
1. Handle the empty body case
  - This change should not cause any issues as we already are using `throwException` in case of non-200 responses 

## Steps to Reproduce
1. Issue can be reproduced by making any valid delete call which returns 204 response

## Possible Implementation
Proposed Code:
```java 
private void processDeleteResponse(Response response) throws RazorpayException {
        if (response == null) {
            throw new RazorpayException("Invalid Response from server");
        } else {
            int statusCode = response.code();
            String responseBody = null;
            JSONObject responseJson = null;

            try {
                responseBody = response.body().string();
               //additional check here
               if(StringUtils.isNotEmpty(responseBody)) {
                responseJson = new JSONObject(responseBody);
               }
            } catch (IOException var6) {
                throw new RazorpayException(var6.getMessage());
            }

            if (statusCode < 200 || statusCode >= 300) {
                this.throwException(statusCode, responseJson);
            }

        }
    }
```

**Comment by ankitdas13** [comment]
@nilayspshah Apologise for the long delay and we missed this [PR](https://github.com/razorpay/razorpay-java/issues/137) , but this issue has been fixed. I appreciate your contribution, please continue .

**Comment by ankitdas13** [comment]
Closing this issue for now and please keep continuing your contribution for this repo
