### ISSUE TITLE
Cannot build on API 31

### ISSUE THREAD

**Issue by Puneet1796** [razorpay/razorpay-java#149]
The `exported` flag that is used to tell the system whether the activity is exported and accessible for deep-links, etc. Since the release of API 31 (Android 12), this flag needs to been explicitly written in the AndroidManifest or the build will fail.

**Comment by ankitdas13** [comment]
@Puneet1796 Sorry for the long delay. seems like you are using [razorpay-android](https://github.com/razorpay/razorpay-android). Could you please confirm, and also let us know if the issue was resolved?

**Comment by ankitdas13** [comment]
Closing this issue for now due to not getting any response, also this issue is not related to this repo. if issue is still persist then create issue in this [repo](https://github.com/razorpay/razorpay-android-sample-app)
