### ISSUE TITLE
support raw requests

### ISSUE THREAD

**Issue by captn3m0** [razorpay/razorpay-java#21]
Setting up basic auth, and nested params is a tough task in Java, maybe we can provide a helper similar to https://github.com/razorpay/razorpay-ruby/pull/47/files to help access to newer APIs?

**Comment by ankit-rzp** [comment]
We can support raw request. Right now, those methods are not exposed (package local). Also supprt for nested params is also there. Will sync with you with the exact requirement,

**Comment by appyschool** [comment]
Post success response, I am trying to check if invoice_id is present in the json response. How to check the null value 

Below is throwing exception

payment. get("invoice_id") !=null

**Comment by sanketrathi2330** [comment]
outdated request.
