### ISSUE TITLE
Doesnt work with Fragment

### ISSUE THREAD

**Issue by tanishq14developer** [razorpay/razorpay-java#260]
Doesnt work with Fragment

**Comment by ankitdas13** [comment]
@tanishq14developer Is the issue related to Android ?

**Comment by tanishq14developer** [comment]
yes

**Comment by ankitdas13** [comment]
@tanishq14developer Could you please create an issue in this [repo](https://github.com/razorpay/razorpay-android)

**Comment by ankitdas13** [comment]
@tanishq14developer This issue is not releated to this repo could you please close this issue and create new issue this [repo](https://github.com/razorpay/razorpay-android-sample-app) ?

**Comment by ankitdas13** [comment]
This issue is not related to this repo. Please open an issue in [repo](https://github.com/razorpay/razorpay-android-sample-app) repo. Closing this issue.
