### ISSUE TITLE
Why I am getting this issue again again 

### ISSUE THREAD

**Issue by tanishq14developer** [razorpay/razorpay-java#261]
E/Rzp: onPaymentError: {"code":"BAD_REQUEST_ERROR","description":"Your payment has been declined as the order is invalid. To pay successfully try initiating the payment again from merchant checkout.","source":"business","step":"payment_initiation","reason":"input_validation_failed","metadata":{"order_id":"KhqK0GLtX9O9ni"}} @ankitdas13

**Comment by ankitdas13** [comment]
@tanishq14developer Have you got this error during checkout or are you using a payment API ? It would be helpfull if you share code snippet

**Comment by tanishq14developer** [comment]
Checkout dependecy api

**Comment by tanishq14developer** [comment]
java.lang.ClassNotFoundException: com.dev.badhatX.badhatXapp.BuildConfig
W/System.err:     at java.lang.Class.classForName(Native Method)
W/System.err:     at java.lang.Class.forName(Class.java:454)
W/System.err:     at java.lang.Class.forName(Class.java:379)
W/System.err:     at com.razorpay.OpinionatedSoln.getBuildConfigValue(OpinionatedSoln.kt:199)
W/System.err:     at com.razorpay.Checkout.open(Checkout.java:141)
W/System.err:     at com.badhatX.badhatXapp.views.RazorpayActivity.startPayment(RazorpayActivity.kt:148)
W/System.err:     at com.badhatX.badhatXapp.views.RazorpayActivity.onCreate(RazorpayActivity.kt:66)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8130)
W/System.err:     at android.app.Activity.performCreate(Activity.java:8110)
W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1343)
W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3781)
W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3977)
W/System.err:     at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:109)
W/System.err:     at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
W/System.err:     at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2374)
W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:106)
W/System.err:     at android.os.Looper.loopOnce(Looper.java:233)
W/System.err:     at android.os.Looper.loop(Looper.java:344)
W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:8248)
W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:589)
W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1071)
W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.dev.badhatX.badhatXapp.BuildConfig" on path: DexPathList[[dex file "/data/data/com.dev.badhatX.badhatXapp/code_cache/.overlay/base.apk/classes8.dex", dex file "/data/data/com.dev.badhatX.badhatXapp/code_cache/.overlay/base.apk/classes3.dex", zip file "/data/app/~~3Cqhch9sXrKw4pYuVM5jlg==/com.dev.badhatX.badhatXapp-Aq9wvJHjSAyTtbjolaGL7Q==/base.apk"],nativeLibraryDirectories=[/data/app/~~3Cqhch9sXrKw4pYuVM5jlg==/com.dev.badhatX.badhatXapp-Aq9wvJHjSAyTtbjolaGL7Q==/lib/arm64, /system/lib64, /system_ext/lib64]]
W/System.err:     at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
W/System.err:     at java.lang.ClassLoader.loadClass(ClassLoader.java:312)

**Comment by ankitdas13** [comment]
@tanishq14developer As much as I know, there is no Checkout dependecy api in this sdk . It looks like you're using this [SDK](https://github.com/razorpay/razorpay-android). Please double check this if it's the one you're using then please raise this issue in this repo which i shared to you.

**Comment by tanishq14developer** [comment]
I am using android sdk @ankitdas13

**Comment by ankitdas13** [comment]
@tanishq14developer It would be great if you could share the link of the SDK you downloaded or dependency code

**Comment by tanishq14developer** [comment]
implementation ‘com.razorpay:checkout:latestversion' @ankitdas13

**Comment by ankitdas13** [comment]
@tanishq14developer could you please check this [repo](https://github.com/razorpay/razorpay-android-sample-app) and let me know?

**Comment by ankitdas13** [comment]
@tanishq14developer Did you get the repo ?

**Comment by ankitdas13** [comment]
@tanishq14developer could you please confirm us

**Comment by ankitdas13** [comment]
This issue is not related to this repo. Please open an issue in [repo](https://github.com/razorpay/razorpay-android-sample-app) repo. Closing this issue.
