### ISSUE TITLE
Freezed Grey Screen after initializing Payment Request

### ISSUE THREAD

**Issue by complexgene** [razorpay/razorpay-java#42]
After starting the checkout code, the razorpay progress bar starts, goes off, after which the payment details needed to be filled up. But that screen is not appearing. After the progress bar goes off, it shows a grey screen and gets freezed. 
It's happening in multiple Android models. Currently using: LENOVO A7010a48 Android 6.0 API 23
I am using RazorPay Version: 1.5.2

**Comment by harman28** [comment]
Closing, unrelated to the java server integration, might be related to the Android SDK.
