### ISSUE TITLE
SDK for Go

### ISSUE THREAD

**Issue by kishaningithub** [razorpay/razorpay-java#43]
Not sure where to raise this, Hence putting here. If inappropriate kindly redirect me on where i should be raising this.

I could see SDK's available for several languages (PHP, Ruby, Python, .NET, Node.js, Java) but i could not find one for [go lang](https://golang.org/) 

My question is, Is a first class support for [go lang](https://golang.org/) in your timeline ?

**Comment by captn3m0** [comment]
@kishaningithub You should have a invite for read-only access to the razorpay/razorpay-go private repo (We plan to open it up soon).

Closing this issue.
