### ISSUE TITLE
Why no tests ?

### ISSUE THREAD

**Issue by kishaningithub** [razorpay/razorpay-java#44]
Why are there no tests for this sdk ?

All i can see are source files and there is not even one test file. This totally reduces my confidence level to use this SDK given it handles secure data.

**Comment by kishaningithub** [comment]
Also, I see that all other SDK's have tests and CI integration except this. 

Given java is the language of choice for many business applications why is it not given importance ?

**Comment by Archit-kumar** [comment]
@kishaningithub  let's contribute by writing test cases.

**Comment by sanketrathi2330** [comment]
outdated request.

**Comment by patrickp-at-work** [comment]
😯 @sanketrathi2330  Can you elaborate how you conclude it is "outdated"? I don't see any tests, except in `.gitignore` 🧐

**Comment by ankitdas13** [comment]
We have added a mock test cases for all modules.

**Comment by ankitdas13** [comment]
Closing this issue for now. if you need any help then please let us know.
