### ISSUE TITLE
Fetch tokens is not working.

### ISSUE THREAD

**Issue by Archit-kumar** [razorpay/razorpay-java#45]
throwing com.razorpay.RazorpayException: BAD_REQUEST_ERROR:The requested URL was not found on the server.

while I am fetching tokens.

**Comment by harman28** [comment]
Sorry for the delay here, noting a response anyway for anyone else who comes looking. If you're getting "URL not found", it's because the feature is not enabled on your account. You can ask for it to be enabled via your merchant dashboard, and retry.
