### ISSUE TITLE
Fetching Bank Transfer with latest SDK fails

### ISSUE THREAD

**Issue by power-coder** [razorpay/razorpay-java#46]
I am using Razorpay Java SDK version 1.3.8 and call to 

> razorpayClient.Payments.fetchBankTransfers

simply fails, on debugging, came to know that the SDK is not able to parse the response.

**Comment by harman28** [comment]
@power-coder Sorry for the delay in response here. We would need a little more info to debug this. I hope your issue was sorted out, but if not, please do share additional context if you can and we can look into this ASAP.
