### ISSUE TITLE
Delete a plan

### ISSUE THREAD

**Issue by sharon-tst** [razorpay/razorpay-java#49]
How can i delete a plan using java. ?

razorpayClient.Plans.delete(String path , JsonObject jsonObject) ;
this method support razorpay but what is the meaning of this two parameter . I can't understand it's meaning . Anybody have face this issue ?

**Comment by harman28** [comment]
@sharon-tst Deletion of a plan is not support as per the API docs: [Link](https://razorpay.com/docs/api/subscriptions/#plans)

**Comment by sharon-tst** [comment]
Thank you for your response
