### ISSUE TITLE
Unable to integrate payment api

### ISSUE THREAD

**Issue by lokesh225** [razorpay/razorpay-java#50]
I am getting "url not found" error while using razorpay payments api.
Can i get some help?

**Comment by captn3m0** [comment]
Please provide a snippet.

**Comment by lokesh225** [comment]
<img width="1051" alt="Screen Shot 2019-06-25 at 3 05 35 PM" src="https://user-images.githubusercontent.com/3285549/60087551-dc46f780-975a-11e9-94eb-f826619482c7.png">
<img width="1273" alt="Screen Shot 2019-06-25 at 3 03 24 PM" src="https://user-images.githubusercontent.com/3285549/60087552-dc46f780-975a-11e9-8bf6-d18fdcd123fa.png">

**Comment by lokesh225** [comment]
@captn3m0 did you get a chance to look into it?

**Comment by captn3m0** [comment]
This doesn't look like a Java Integration issue. (Likely a configuration issue on your account)

Can you please create a ticket via razorpay.com/support and our support team will be able to take a look?
