### ISSUE TITLE
PaymentClient#fetchAll only returns 10 

### ISSUE THREAD

**Issue by siddadel** [razorpay/razorpay-java#59]
At People's Archive of Rural India, we are trying to use the Java bindings of Razorpay REST API to get a list of our subscribers' pancard details. These are entered as notes only when the subscriber makes the first payment. These payments are thus way back in history.

When trying to fetchAll, the client only returns the latest 10 payments. I see that in the REST API the count has been set to default at 10. Is there anyway that we can change the count or paginate? 

Properties prop = new Properties();
		prop.load(App.class.getResourceAsStream("/application.properties"));
		RazorpayClient razorpayClient = new RazorpayClient(prop.getProperty("key"), prop.getProperty("secret"));
		List<Payment> payments = razorpayClient.Payments.fetchAll();
		System.out.println(payments.size());
		
		for (Payment p : payments) {
			Object notes = p.get("notes");
			if (notes instanceof JSONObject) {
				System.out.println(((JSONObject) notes).get("customer_pan"));
			}
		}

**Comment by harman28** [comment]
You can pass 'count' as an additional parameter to fetch a higher number of payments. Other parameters are noted here: [Link](https://razorpay.com/docs/api/payments/#query-parameters_)
