### ISSUE TITLE
Segment Class with ASCII character's causes proguard error

### ISSUE THREAD

**Issue by vipulasri** [razorpay/razorpay-java#6]
Razorpay `v1.0.2` and also tested on `v1.2.0` causes the error with Segment Class having ASCII character in class name while applying proguard.

Android gradle version: 2.3.0
Android Studio: 2.3

I am having this error: 
`Error:org.gradle.api.UncheckedIOException: java.io.IOException: Failed to read zip file 'app/build/intermediates/transforms/proguard/release/jars/3/1f/main.jar'.`

> Caused by: java.io.IOException: Failed to read stored entry 'com/razorpay/Segment$ۥ.class'.
> 	at com.android.apkzlib.zip.CentralDirectory.readEntry(CentralDirectory.java:367)
> 	at com.android.apkzlib.zip.CentralDirectory.makeFromData(CentralDirectory.java:225)
> 	... 36 more

**Comment by mb-14** [comment]
@vipulasri This library is meant to be used by your backend service and not your android app. For integrating our mobile SDK, please go through this page: https://github.com/razorpay/razorpay-android-sample-app/releases

**Comment by rcode** [comment]
I am facing this same issue when using the RazorPay Android SDK with proguard configured.
`Caused by: java.io.IOException: Failed to read stored entry 'com/razorpay/Segment$ۥ.class'.`
Gradle version 3.3

I have already added the following rules in my proguard rules file
https://github.com/razorpay/razorpay-android-sample-app/blob/master/proguard-project.txt

Here is the stack trace of the exception during grade build:
.
.
> 14:34:00.888 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
> 14:34:00.889 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Execution failed for task ':app:packageDevRelease'.
> 14:34:00.889 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] > java.io.IOException: Failed to read zip file '/Users/Rahul/Downloads/doctor24x7-android/app/build/intermediates/transforms/proguard/dev/release/jars/3/1f/main.jar'.
.
.
> 14:34:00.893 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: org.gradle.api.UncheckedIOException: java.io.IOException: Failed to read zip file '/Users/Rahul/Downloads/doctor24x7-android/app/build/intermediates/transforms/proguard/dev/release/jars/3/1f/main.jar'.
.
.
> 14:34:00.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 20 more
> 14:34:00.895 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Failed to read zip file '/Users/Rahul/Downloads/doctor24x7-android/app/build/intermediates/transforms/proguard/dev/release/jars/3/1f/main.jar'.
.
.
> 14:34:00.897 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] **Caused by: java.io.IOException: Failed to read stored entry 'com/razorpay/Segment$ۥ.class'.**
.
.
> 14:34:00.898 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Failed to read data descriptor record.
.
.
> 14:34:00.898 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] 	... 37 more
> 14:34:00.899 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Caused by: java.io.IOException: Incorrect value for field 'CRC32': value is 122376255 but 2318257738 expected.
.
. 
>
