### ISSUE TITLE
[Java] Integration capture payment giving an error #94

### ISSUE THREAD

**Issue by DhiralKaniya** [razorpay/razorpay-java#60]
I am doing razorpay java API integration with spring boot. 

Below is the razorpay version which I am using.
```
<dependency>
    <groupId>com.razorpay</groupId>
    <artifactId>razorpay-java</artifactId>
    <version>1.3.8</version>
</dependency>
```

Capture payment API is giving me an error. 
Below code snippet which I am using to capture payment.
```
public static String capturePayment(String paymentid){
        try {
            JSONObject options = new JSONObject();
            options.put("amount", 500.00);
            CustomRazopayClient.getRazopayClient().Payments.capture(paymentid, options);
            return "success";
        }catch (Exception e){
            return e.getLocalizedMessage();
        }
    }
```
Error which I am getting
`"BAD_REQUEST_ERROR:Capture amount must be equal to the amount authorized"`

I have tried an amount as 500. 
Can anyone help here?

Just for info:- Amount is validated.
Below is the screenshot for reference.

<img width="1441" alt="Screenshot 2019-07-28 at 11 18 20 AM" src="https://user-images.githubusercontent.com/21332852/62002996-eaf34680-b12c-11e9-9f66-ce15a772ad5f.png">

**Comment by captn3m0** [comment]
The amount must be specified in paise, please use 50000 instead.

**Comment by muhtadii** [comment]
One of the reason it occurs is, when you have Convenience Fee Model option enabled in the Settings → Fee Bearer section of the Razorpay Dashboard.
