### ISSUE TITLE
Card Detail Fetch

### ISSUE THREAD

**Issue by pravesh98** [razorpay/razorpay-java#67]
Cannot Find Client code for 
/payments/:id/card

https://razorpay.com/docs/api/payments/#fetch-the-card-details-for-a-payment

@ankit-rzp

**Comment by gourav145** [comment]
but i does not return card expiry date ,  any idae?

**Comment by harman28** [comment]
@pravesh98 While we don't have support for the API endpoint you've linked, we do support sending of an additional parameter called `expand[]=card` in the fetch call, which will give you all cards details. More details here: [Link](https://razorpay.com/docs/api/payments/#query-parameters)

@gourav145 Expiry is not made visible by default for security reasons. You can raise a request from your merchant dashboard to access this data if needed, and it will be enabled for your account after approval.
