### ISSUE TITLE
Token

### ISSUE THREAD

**Issue by pravesh98** [razorpay/razorpay-java#68]
How exactly token here is working? 
 i tried to fetch the token, i got error while accessing API 
List<Token> tokens = razorpayClient.Customers.fetchTokens(customerId);

Error:-
com.razorpay.RazorpayException: BAD_REQUEST_ERROR:The requested URL was not found on the server.

@ankit-rzp

**Comment by harman28** [comment]
Sorry for the delay here, noting a response anyway for anyone else who comes looking. If you're getting "URL not found", it's because the feature is not enabled on your account. You can ask for it to be enabled via your merchant dashboard, and retry.
