### ISSUE TITLE
Capturing payments using Java Sdk in Android

### ISSUE THREAD

**Issue by chitra-bahadur** [razorpay/razorpay-java#78]
Trying to capture the payments using java sdk in android, In debug mode its working fine but in production app is crashing. This issue may be related with proguard . Without Razorpay Java SDK its working fine

**Comment by harman28** [comment]
Sorry for the delay here. We'd need a little more info here to debug this, such as the details of the crash or error. I hope this worked out for you, but if not, please feel free to share additional info so we can check it out at once.
